### ISSUE TITLE
Can't build anymore

### ISSUE THREAD

**Issue by Ambrase** [oliora/ppconsul#53] opened 2020-05-16 09:06 UTC
I have the following error when i'm trying to build the current master:

[  6%] Building CXX object src/CMakeFiles/ppconsul.dir/agent.cpp.o

[  9%] Building CXX object src/CMakeFiles/ppconsul.dir/catalog.cpp.o

[ 11%] Building CXX object src/CMakeFiles/ppconsul.dir/consul.cpp.o

ppconsul/src/consul.cpp:91:13: error: function 'ppconsul::Consul& ppconsul::Consul::operator=(ppconsul::Consul&&)' defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ''
     Consul& Consul::operator= (Consul &&op) PPCONSUL_NOEXCEPT = default;
             ^~~~~~
make[2]: *** [src/CMakeFiles/ppconsul.dir/build.make:89: src/CMakeFiles/ppconsul.dir/consul.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:146: src/CMakeFiles/ppconsul.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
Boost 1.73

**Comment by oliora** [comment] 2020-05-16 11:10
This is caused by using old ABI, i.e. compiling with `CXX="g++-7 -D_GLIBCXX_USE_CXX11_ABI=0"`.

**Comment by oliora** [comment] 2020-05-16 11:50
I've pushed the fix. Please verify and reopen the issue if you still have problem.

**Closed by oliora** 2020-05-16 11:50 UTC
